// <auto-generated />
namespace GlobalCollege.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class _2020080101 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_2020080101));
        
        string IMigrationMetadata.Id
        {
            get { return "202008010926043_2020-08-01-01"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
