// <auto-generated />
namespace GlobalCollege.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class _2020080201 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_2020080201));
        
        string IMigrationMetadata.Id
        {
            get { return "202008020452219_2020-08-02-01"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
